/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <linux/inotify.h>

#include <glib.h>

#include <libinotify/libinotify.h>
/* Header for class c_libInotify */

#ifndef _Included_utils_c_libInotify
#define _Included_utils_c_libInotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_libInotify
 * Method:    registerWatch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_utils_c_libInotify_registerWatch(JNIEnv *env, jclass class, jstring filename);

/*
 * Class:     c_libInotify
 * Method:    removeWatch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_utils_c_libInotify_removeWatch
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
